---
- name: Ground Software Enviromnent
  hosts: localhost
  vars:
    user: 'soeren'
    user_home: '/home/soeren'
    software_dir: '/opt/'
    java_version: '21.0.9-tem'
    node_version: '24'

  tasks:
    - name: Check if SDKMAN is installed
      stat:
        path: '{{ user_home }}/.sdkman'
      register: sdkman_installed

    - name: Install SDKMAN
      shell: |
        curl -s "https://get.sdkman.io" | bash
        source '{{ user_home }}/.sdkman/bin/sdkman-init.sh'
      args:
        executable: /bin/bash
      when: not sdkman_installed.stat.exists

    - name: Install sdk packages
      shell: |
        source '{{ user_home }}/.sdkman/bin/sdkman-init.sh'
        sdk install {{ item.package }}
      loop:
        - { package: 'kotlin' }
        - { package: 'maven' }
        - { package: 'visualvm' }
        - { package: 'gradle' }
        - { package: 'java {{ java_version }}' }
      args:
        executable: /bin/bash

    - name: Check if NVM is installed
      stat:
        path: '{{ user_home }}/.nvm'
      register: nvm_installed

    - name: Install NVM
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
      args:
        executable: /bin/bash
      when: not nvm_installed.stat.exists

    - name: Install Node.js via nvm
      shell: |
        export NVM_DIR="{{ user_home }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install {{ node_version }}
      args:
        executable: /bin/bash

    - name: Ensure path setup
      lineinfile:
        path: '{{ user_home }}/.bashrc'
        line: 'export {{ item.env_var }}={{ item.path }}'
      loop:
        - { env_var: 'PATH', path: '$PATH:./local/bin' }

