---
- name: Ground Software Environment
  hosts: localhost
  vars:
    user: 'soeren'
    user_home: '/home/soeren'

  tasks:
    - name: Install VS Code
      become: yes
      become_method: sudo
      community.general.snap:
        name: code
        classic: yes

    - name: Check if OpenCode is already installed
      stat:
        path: "{{ user_home }}/.opencode/bin/opencode"
      register: opencode_check
      changed_when: false

    - name: Install OpenCode
      shell: curl -fsSL https://opencode.ai/install | bash
      args:
        executable: /bin/bash
      when: not opencode_check.stat.exists

    - name: Install VS Code extensions
      shell: |
        code --install-extension ms-python.python
      args:
        executable: /bin/bash

    - name: Install Chromium
      become: yes
      become_method: sudo
      community.general.snap:
        name: chromium

    - name: Install Docker Engine and Docker Compose
      become: yes
      become_method: sudo
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Add user to docker group
      become: yes
      become_method: sudo
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Ensure Docker service is started and enabled
      become: yes
      become_method: sudo
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Portainer container
      become: yes
      become_method: sudo
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        ports:
          - "9000:9000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

