---
- name: Ground Software Environment
  hosts: localhost
  vars:
    user: 'soeren'
    user_home: '/home/soeren'

  tasks:
    - name: Install VS Code
      become: yes
      become_method: sudo
      community.general.snap:
        name: code
        classic: yes

    - name: Check if OpenCode is already installed
      stat:
        path: "{{ user_home }}/.opencode/bin/opencode"
      register: opencode_check
      changed_when: false

    - name: Install OpenCode
      shell: curl -fsSL https://opencode.ai/install | bash
      args:
        executable: /bin/bash
      when: not opencode_check.stat.exists

    - name: Install VS Code extensions
      shell: |
        code --install-extension ms-python.python
      args:
        executable: /bin/bash

    - name: Install Chromium
      become: yes
      become_method: sudo
      community.general.snap:
        name: chromium

    - name: Install Docker Engine and Docker Compose
      become: yes
      become_method: sudo
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Add user to docker group
      become: yes
      become_method: sudo
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Ensure Docker service is started and enabled
      become: yes
      become_method: sudo
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Portainer container
      become: yes
      become_method: sudo
      shell: |
        docker run -d \
          --name portainer \
          --restart=always \
          -p 9000:9000 \
          -p 9443:9443 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v portainer_data:/data \
          portainer/portainer-ce:latest
      args:
        executable: /bin/bash
      register: portainer_result
      failed_when: portainer_result.rc != 0 and 'already in use' not in portainer_result.stderr
      changed_when: portainer_result.rc == 0

