---
- name: Private Tools Setup
  hosts: localhost
  vars:
    user: 'soeren'
    user_home: '/home/soeren'

  tasks:
    - name: Check if Neovim is installed
      shell: nvim --version | head -n1
      register: nvim_current_version
      failed_when: false
      changed_when: false

    - name: Display current Neovim version
      debug:
        msg: "Current Neovim version: {{ nvim_current_version.stdout if nvim_current_version.rc == 0 else 'Not installed' }}"

    - name: Remove old Neovim AppImage
      file:
        path: "{{ user_home }}/.local/bin/nvim"
        state: absent
      when: nvim_current_version.rc == 0

    - name: Ensure .local/bin directory exists
      file:
        path: "{{ user_home }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Get latest Neovim version
      shell: |
        curl -s https://api.github.com/repos/neovim/neovim/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/'
      register: latest_nvim_version
      changed_when: false

    - name: Download and install latest Neovim AppImage
      shell: |
        cd /tmp
        curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
        chmod u+x nvim-linux-x86_64.appimage
        mv nvim-linux-x86_64.appimage {{ user_home }}/.local/bin/nvim
      args:
        executable: /bin/bash

    - name: Verify Neovim installation
      shell: "{{ user_home }}/.local/bin/nvim --version | head -n1"
      register: new_nvim_version
      changed_when: false

    - name: Display installed Neovim version
      debug:
        msg: "Installed Neovim version: {{ new_nvim_version.stdout }}"

    - name: Check if LazyVim is already installed
      stat:
        path: "{{ user_home }}/.config/nvim"
      register: lazyvim_check
      changed_when: false

    - name: Remove old backup if it exists
      file:
        path: "{{ user_home }}/.config/nvim.bak"
        state: absent
      when: lazyvim_check.stat.exists

    - name: Backup existing Neovim config if present
      command: mv {{ user_home }}/.config/nvim {{ user_home }}/.config/nvim.bak
      when: lazyvim_check.stat.exists

    - name: Clone LazyVim starter configuration
      git:
        repo: 'https://github.com/LazyVim/starter'
        dest: "{{ user_home }}/.config/nvim"
        depth: 1

    - name: Remove .git folder from LazyVim config
      file:
        path: "{{ user_home }}/.config/nvim/.git"
        state: absent

    - name: Get latest lazygit version
      shell: |
        curl -s https://api.github.com/repos/jesseduffield/lazygit/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/'
      register: lazygit_version
      changed_when: false

    - name: Download and install lazygit from GitHub
      shell: |
        cd /tmp
        VERSION="{{ lazygit_version.stdout }}"
        curl -LO "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${VERSION#v}_Linux_x86_64.tar.gz"
        tar -xzf "lazygit_${VERSION#v}_Linux_x86_64.tar.gz"
        mv lazygit {{ user_home }}/.local/bin/lazygit
        chmod +x {{ user_home }}/.local/bin/lazygit
        rm -f "lazygit_${VERSION#v}_Linux_x86_64.tar.gz"
      args:
        executable: /bin/bash

    - name: Set Omarchy-style keyboard shortcuts
      shell: |
        # Terminal launcher (Super+Return)
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'Launch Terminal'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'gnome-terminal'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Super>Return'"

        # Browser launcher (Super+Shift+B)
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name "'Launch Browser'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command "'chromium'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding "'<Super><Shift>b'"

        # File manager (Super+Shift+F)
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name "'Launch File Manager'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command "'nautilus'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding "'<Super><Shift>f'"

        # Neovim (Super+Shift+N)
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name "'Launch Neovim'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command "'gnome-terminal -- nvim'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding "'<Super><Shift>n'"

        # Lazygit (Super+Shift+G)
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/name "'Launch Lazygit'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/command "'gnome-terminal -- {{ user_home }}/.local/bin/lazygit'"
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/binding "'<Super><Shift>g'"

        # Close window (Super+W)
        dconf write /org/gnome/desktop/wm/keybindings/close "['<Super>w']"

        # Toggle fullscreen (Super+F)
        dconf write /org/gnome/desktop/wm/keybindings/toggle-fullscreen "['<Super>f']"

        # Switch workspaces (Super+1/2/3/4)
        dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-1 "['<Super>1']"
        dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-2 "['<Super>2']"
        dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-3 "['<Super>3']"
        dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-4 "['<Super>4']"

        # Move window to workspace (Super+Shift+1/2/3/4)
        dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-1 "['<Super><Shift>1']"
        dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-2 "['<Super><Shift>2']"
        dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-3 "['<Super><Shift>3']"
        dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-4 "['<Super><Shift>4']"

        # Register custom keybindings
        dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']"
      args:
        executable: /bin/bash

    - name: Install LazyVim dependencies via apt
      become: yes
      become_method: sudo
      apt:
        name:
          - build-essential
          - ripgrep
          - fzf
          - fish
          - luarocks
        state: present
        update_cache: yes

    - name: Get latest fd version
      shell: |
        curl -s https://api.github.com/repos/sharkdp/fd/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/'
      register: fd_version
      changed_when: false

    - name: Download and install fd
      shell: |
        cd /tmp
        VERSION="{{ fd_version.stdout }}"
        curl -LO "https://github.com/sharkdp/fd/releases/latest/download/fd-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        tar -xzf "fd-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        mv "fd-${VERSION}-x86_64-unknown-linux-gnu/fd" {{ user_home }}/.local/bin/fd
        chmod +x {{ user_home }}/.local/bin/fd
        rm -rf "fd-${VERSION}-x86_64-unknown-linux-gnu" "fd-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      args:
        executable: /bin/bash

    - name: Download and install ast-grep
      shell: |
        cd /tmp
        curl -LO https://github.com/ast-grep/ast-grep/releases/latest/download/app-x86_64-unknown-linux-gnu.zip
        unzip -o app-x86_64-unknown-linux-gnu.zip
        chmod +x ast-grep sg
        mv ast-grep {{ user_home }}/.local/bin/ast-grep
        mv sg {{ user_home }}/.local/bin/sg
        rm -f app-x86_64-unknown-linux-gnu.zip
      args:
        executable: /bin/bash

    - name: Fix nvim cache directory permissions for lazygit
      file:
        path: "{{ user_home }}/.cache/nvim"
        state: directory
        mode: '0755'
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes

    - name: Verify tool installations
      shell: |
        echo "ripgrep: $(rg --version | head -n1)"
        echo "fd: $({{ user_home }}/.local/bin/fd --version)"
        echo "fzf: $(fzf --version)"
        echo "fish: $(fish --version)"
        echo "luarocks: $(luarocks --version | head -n1)"
        echo "ast-grep: $({{ user_home }}/.local/bin/ast-grep --version)"
        echo "gcc: $(gcc --version | head -n1)"
      args:
        executable: /bin/bash
      register: tool_versions
      changed_when: false

    - name: Display installed tool versions
      debug:
        msg: "{{ tool_versions.stdout_lines }}"
