---
- name: Ground Software Enviromnent
  hosts: localhost
  vars:
    user: 'soeren'
    user_home: '/home/soeren'
    software_dir: '/opt/'
    java_version: ''
    node_version: ''
    maven_version: ''
    gradle_version: ''

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      # become: yes
      apt:
        name:
          - curl
          - git
    - name: Install snap packages
      community.general.snap:
        name:
          - signal-desktop
        classic: yes


    - name: Check installed versions
      stat:
        path: '{{ software_dir }}/{{ item.name }}/default'
      loop:
        - { name: 'node'}
        - { name: 'java'}
        - { name: 'maven'}
        - { name: 'gradle'}
      register: path_checks
      failed_when: false
      changed_when: false

    - name: Check installed versions
      shell: '{{ item.command }}'
      loop:
        - { command: 'node --version' }
        - { command: 'java --version 2>&1 | head -n 1' }
        - { command: 'mvn --version | head -n 1' }
        - { command: 'gradle --version | head -n 1' }
      register: version_checks
      failed_when: false
      changed_when: false


    - name: Ensure path setup 
      lineinfile:
        path: '{{ user_home }}/.bashrc'
        line: 'export {{ item.env_var }}={{ item.path }}'
      loop:
        - { env_var: 'JAVA_HOME', path: '{{ software_dir }}/java/default' }
        - { env_var: 'NODE_HOME', path: '{{ software_dir }}/node/default' }
        - { env_var: 'MAVEN_HOME', path: '{{ software_dir }}/maven/default' }
        - { env_var: 'GRADLE_HOME', path: '{{ software_dir }}/gradle/default' }
        - { env_var: 'PATH', path: '$PATH:./local/bin:$JAVA_HOME/bin:$NODE_HOME/bin:$MAVEN_HOME/bin:$GRADLE_HOME/bin' }

    - name: Load env variables
      shell: source '{{ user_home }}/.bashrc'

