---
# Master playbook for development environment setup
# Run with: ansible-playbook main.yml
# Or run specific sections with tags: ansible-playbook main.yml --ask-become-pass

- name: Prompt for general preferences 
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: install_neovim
      prompt: "Do you want to install Neovim? (yes/no)"
      default: "yes"
      private: false
    - name: install_additional_tools
      prompt: "Do you want to install additional tools? (yes/no)"
      default: "yes"
      private: false
    - name: install_keyboard_shortcuts
      prompt: "Do you want to install keyboard shortcuts? (yes/no)"
      default: "yes"
      private: false
  tasks:
    - name: Set general preferences
      set_fact:
        should_install_neovim: "{{ install_neovim | bool }}"
        should_install_additional_tools: "{{ install_additional_tools | bool }}"
        should_install_keyboard_shortcuts: "{{ install_keyboard_shortcuts | bool }}"
        cacheable: true

- name: Prompt for LazyVim installation
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: install_lazyvim
      prompt: "Do you want to install LazyVim (includes lazygit)? (yes/no)"
      default: "yes"
      private: false
  tasks:
    - name: Set LazyVim installation preference
      set_fact:
        should_install_lazyvim: "{{ install_lazyvim | bool }}"
        cacheable: true
      when: hostvars['localhost']['should_install_neovim'] | default(false)

- name: Prompt for additional tools
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: install_game_dev
      prompt: "Do you want to install game dev tools? (yes/no)"
      default: "yes"
      private: false
    - name: install_speedcrunch
      prompt: "Do you want to install speedcrunch? (yes/no)"
      default: "no"
      private: false
    - name: install_clojure
      prompt: "Do you want to install Clojure tools (rlwrap, babashka, clojure-cli)? (yes/no)"
      default: "no"
      private: false
    - name: install_nerdfonts
      prompt: "Do you want to install Nerd Fonts (FiraCode, Hack, JetBrainsMono, Meslo)? (yes/no)"
      default: "yes"
      private: false
    - name: install_starship
      prompt: "Do you want to install Starship prompt? (yes/no)"
      default: "yes"
      private: false
    - name: install_rocm
      prompt: "Do you want to install ROCm (AMD GPU compute platform for Ubuntu 24.04)? (yes/no)"
      default: "no"
      private: false
  tasks:
    - name: Set additional tools installation preferences
      set_fact:
        should_install_game_dev: "{{ install_game_dev | bool }}"
        should_install_speedcrunch: "{{ install_speedcrunch | bool }}"
        should_install_clojure: "{{ install_clojure | bool }}"
        should_install_nerdfonts: "{{ install_nerdfonts | bool }}"
        should_install_starship: "{{ install_starship | bool }}"
        should_install_rocm: "{{ install_rocm | bool }}"
        cacheable: true
      when: hostvars['localhost']['should_install_additional_tools'] | default(false)


- name: Prompt for keyboard shortcuts
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: install_shortcuts
      prompt: "Do you want to install a keyboard shortcuts? (soeren)"
      default: "soeren"
      private: false
  tasks:
    - name: Set keyboard shortcut preference
      set_fact:
        should_install_keyboard_soeren: "{{ install_shortcuts | bool }}"
        cacheable: true
      when: hostvars['localhost']['should_install_keyboard_shortcuts'] | default(false)

- name: Prompt for configuration files
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: copy_default_configs
      prompt: "Do you want to copy default configuration files? (yes/no)"
      default: "yes"
      private: false
  tasks:
    - name: Set configuration files preference
      set_fact:
        should_copy_default_configs: "{{ copy_default_configs | bool }}"
        cacheable: true

- name: Prompt for git configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: git_user_name
      prompt: "Enter your git user name (leave empty to skip git config)"
      default: ""
      private: false
    - name: git_user_email
      prompt: "Enter your git user email (leave empty to skip git config)"
      default: ""
      private: false
  tasks:
    - name: Set git configuration preferences
      set_fact:
        should_configure_git: "{{ git_user_name | default('') != '' or git_user_email | default('') != '' }}"
        git_configured_name: "{{ git_user_name | default('') }}"
        git_configured_email: "{{ git_user_email | default('') }}"
        cacheable: true

# Base system packages
- import_playbook: playbooks/base/packages.yml
  tags: [base, packages]

- import_playbook: playbooks/base/signal.yml
  tags: [base, signal]

# Configuration files
- import_playbook: playbooks/base/copy-default-configurations.yml
  tags: [base, configs]
  when: hostvars['localhost']['should_copy_default_configs'] | default(false)

# Git configuration
- import_playbook: playbooks/development/git-config.yml
  tags: [base, git-config]
  when: hostvars['localhost']['should_configure_git'] | default(false)

# Development environment managers
- import_playbook: playbooks/development/sdkman.yml
  tags: [base, sdkman]

- import_playbook: playbooks/development/nvm.yml
  tags: [base, nvm]

# Java/JVM tools (require SDKMAN)
- import_playbook: playbooks/development/java.yml
  tags: [base, java]

- import_playbook: playbooks/development/kotlin.yml
  tags: [base, kotlin]

- import_playbook: playbooks/development/maven.yml
  tags: [base, maven]

- import_playbook: playbooks/development/gradle.yml
  tags: [base, gradle]

- import_playbook: playbooks/development/visualvm.yml
  tags: [base, visualvm]

# Node.js (requires NVM)
- import_playbook: playbooks/development/nodejs.yml
  tags: [base, nodejs]

# IDEs and editors
- import_playbook: playbooks/development/vscode.yml
  tags: [base, vscode]

- import_playbook: playbooks/development/vscode-plugins-soeren.yml
  tags: [base, vscode-plugins]

- import_playbook: playbooks/development/opencode.yml
  tags: [base, opencode]

- import_playbook: playbooks/development/neovim.yml
  tags: [base, neovim]
  when: hostvars['localhost']['should_install_neovim'] | default(true)

- import_playbook: playbooks/development/neovim-deps.yml
  tags: [base, neovim-deps]
  when: hostvars['localhost']['should_install_neovim'] | default(true)

- import_playbook: playbooks/development/nerdfonts.yml
  tags: [base, nerdfonts]
  when: hostvars['localhost']['should_install_nerdfonts'] | default(false)

- import_playbook: playbooks/development/lazyvim.yml
  tags: [base, lazyvim]
  when: hostvars['localhost']['should_install_lazyvim'] | default(true)

# Docker and containers
- import_playbook: playbooks/development/docker.yml
  tags: [base, docker]

- import_playbook: playbooks/development/portainer.yml
  tags: [base, portainer]

# Development tools
- import_playbook: playbooks/development/lazygit.yml
  tags: [base, lazygit]
  when: hostvars['localhost']['should_install_lazyvim'] | default(true)

- import_playbook: playbooks/development/fd.yml
  tags: [base, fd]

- import_playbook: playbooks/development/ast-grep.yml
  tags: [base, ast-grep]

- import_playbook: playbooks/development/tmux.yml
  tags: [base, tmux]

- import_playbook: playbooks/development/starship.yml
  tags: [base, starship]
  when: hostvars['localhost']['should_install_starship'] | default(false)

- import_playbook: playbooks/development/rocm.yml
  tags: [base, rocm]
  when: hostvars['localhost']['should_install_rocm'] | default(false)

# Clojure
- import_playbook: playbooks/development/rlwrap.yml
  tags: [base, clojure, rlwrap]
  when: hostvars['localhost']['should_install_clojure'] | default(false)

- import_playbook: playbooks/development/babashka.yml
  tags: [base, clojure, babashka]
  when: hostvars['localhost']['should_install_clojure'] | default(false)

- import_playbook: playbooks/development/clojure-cli.yml
  tags: [base, clojure, clojure-cli]
  when: hostvars['localhost']['should_install_clojure'] | default(false)

# Game development
- import_playbook: playbooks/development/odin.yml
  tags: [base, odin]
  when: hostvars['localhost']['should_install_game_dev'] | default(false)

- import_playbook: playbooks/development/blockbench.yml
  tags: [base, blockbench]
  when: hostvars['localhost']['should_install_game_dev'] | default(false)

# Applications
- import_playbook: playbooks/applications/chromium.yml
  tags: [base, chromium]

- import_playbook: playbooks/applications/speedcrunch.yml
  tags: [base, speedcrunch]
  when: hostvars['localhost']['should_install_speedcrunch'] | default(false)

# Keyboard shortcuts
- import_playbook: playbooks/keyboard-shortcuts/soeren.yml
  tags: [base, keyboard-shortcuts]
  when: hostvars['localhost']['should_install_keyboard_shortcuts'] | default(false)
