---
# Master playbook for development environment setup
# Run with: ansible-playbook main.yml --ask-become-pass
# Or run specific sections with tags
#
# Preferences are managed in preferences.json
# Copy preferences.example.json to preferences.json and customize

# Load preferences
- name: Load preferences
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check if preferences.json exists
      stat:
        path: "{{ playbook_dir }}/preferences.json"
      register: prefs_file

    - name: Fail if preferences.json not found
      fail:
        msg: |
          preferences.json not found!

          Please create it by copying the example:
            cp preferences.example.json preferences.json

          Then edit preferences.json to customize your installation.
      when: not prefs_file.stat.exists

    - name: Read preferences.json
      include_vars:
        file: "{{ playbook_dir }}/preferences.json"
        name: prefs

    - name: Set preferences as facts
      set_fact:
        should_install_base_packages: "{{ prefs.install_base_packages | bool }}"
        should_install_signal: "{{ prefs.install_signal | bool }}"
        should_copy_default_configs: "{{ prefs.copy_default_configs | bool }}"
        should_configure_git: "{{ prefs.configure_git | bool }}"
        git_configured_name: "{{ prefs.git_user_name | default('') }}"
        git_configured_email: "{{ prefs.git_user_email | default('') }}"
        should_install_jvm: "{{ prefs.install_jvm | bool }}"
        should_install_nodejs: "{{ prefs.install_nodejs | bool }}"
        should_install_vscode: "{{ prefs.install_vscode | bool }}"
        should_install_opencode: "{{ prefs.install_opencode | bool }}"
        should_install_neovim: "{{ prefs.install_neovim | bool }}"
        should_install_lazyvim: "{{ prefs.install_lazyvim | bool }}"
        should_install_docker: "{{ prefs.install_docker | bool }}"
        should_install_ast_grep: "{{ prefs.install_ast_grep | bool }}"
        should_install_tmux: "{{ prefs.install_tmux | bool }}"
        should_install_zellij: "{{ prefs.install_zellij | bool }}"
        should_install_starship: "{{ prefs.install_starship | bool }}"
        should_install_rocm: "{{ prefs.install_rocm | bool }}"
        should_install_clojure: "{{ prefs.install_clojure | bool }}"
        should_install_game_dev: "{{ prefs.install_game_dev | bool }}"
        should_install_chromium: "{{ prefs.install_chromium | bool }}"
        should_install_speedcrunch: "{{ prefs.install_speedcrunch | bool }}"
        should_install_keyboard_shortcuts: "{{ prefs.install_keyboard_shortcuts | bool }}"
        cacheable: true

    - name: Display loaded preferences
      debug:
        msg:
          - "Loaded preferences:"
          - "  Base packages: {{ should_install_base_packages }}"
          - "  Signal: {{ should_install_signal }}"
          - "  Copy configs: {{ should_copy_default_configs }}"
          - "  Git config: {{ should_configure_git }}"
          - "  JVM: {{ should_install_jvm }}"
          - "  Node.js: {{ should_install_nodejs }}"
          - "  VS Code: {{ should_install_vscode }}"
          - "  OpenCode: {{ should_install_opencode }}"
          - "  Neovim: {{ should_install_neovim }}"
          - "  LazyVim: {{ should_install_lazyvim }}"
          - "  Docker: {{ should_install_docker }}"
          - "  ast-grep: {{ should_install_ast_grep }}"
          - "  tmux: {{ should_install_tmux }}"
          - "  Zellij: {{ should_install_zellij }}"
          - "  Starship: {{ should_install_starship }}"
          - "  ROCm: {{ should_install_rocm }}"
          - "  Clojure: {{ should_install_clojure }}"
          - "  Game dev: {{ should_install_game_dev }}"
          - "  Chromium: {{ should_install_chromium }}"
          - "  SpeedCrunch: {{ should_install_speedcrunch }}"
          - "  Keyboard shortcuts: {{ should_install_keyboard_shortcuts }}"

# Base system packages
- import_playbook: playbooks/base/packages.yml
  tags: [base, packages]
  when: hostvars['localhost']['should_install_base_packages'] | default(true)

- import_playbook: playbooks/base/signal.yml
  tags: [base, signal]
  when: hostvars['localhost']['should_install_signal'] | default(false)

# Configuration files
- import_playbook: configs/soeren/copy-config-soeren.yml
  tags: [base, configs]
  when: hostvars['localhost']['should_copy_default_configs'] | default(false)

# Git configuration
- import_playbook: playbooks/development/git-config.yml
  tags: [base, git-config]
  when: hostvars['localhost']['should_configure_git'] | default(false)

# Development environment managers
- import_playbook: playbooks/development/sdkman.yml
  tags: [base, sdkman]
  when: hostvars['localhost']['should_install_jvm'] | default(false)

- import_playbook: playbooks/development/nvm.yml
  tags: [base, nvm]
  when: hostvars['localhost']['should_install_nodejs'] | default(false)

# Java/JVM tools (require SDKMAN)
- import_playbook: playbooks/development/java.yml
  tags: [base, java]
  when: hostvars['localhost']['should_install_jvm'] | default(false)

- import_playbook: playbooks/development/kotlin.yml
  tags: [base, kotlin]
  when: hostvars['localhost']['should_install_jvm'] | default(false)

- import_playbook: playbooks/development/maven.yml
  tags: [base, maven]
  when: hostvars['localhost']['should_install_jvm'] | default(false)

- import_playbook: playbooks/development/gradle.yml
  tags: [base, gradle]
  when: hostvars['localhost']['should_install_jvm'] | default(false)

- import_playbook: playbooks/development/visualvm.yml
  tags: [base, visualvm]
  when: hostvars['localhost']['should_install_jvm'] | default(false)

# Node.js (requires NVM)
- import_playbook: playbooks/development/nodejs.yml
  tags: [base, nodejs]
  when: hostvars['localhost']['should_install_nodejs'] | default(false)

# IDEs and editors
- import_playbook: playbooks/development/vscode.yml
  tags: [base, vscode]
  when: hostvars['localhost']['should_install_vscode'] | default(false)

- import_playbook: playbooks/development/vscode-plugins-soeren.yml
  tags: [base, vscode-plugins]
  when: hostvars['localhost']['should_install_vscode'] | default(false)

- import_playbook: playbooks/development/opencode.yml
  tags: [base, opencode]
  when: hostvars['localhost']['should_install_opencode'] | default(false)

- import_playbook: playbooks/development/neovim.yml
  tags: [base, neovim]
  when: hostvars['localhost']['should_install_neovim'] | default(false)

- import_playbook: playbooks/development/neovim-deps.yml
  tags: [base, neovim-deps]
  when: hostvars['localhost']['should_install_neovim'] | default(false)

- import_playbook: playbooks/development/nerdfonts.yml
  tags: [base, nerdfonts]
  when: hostvars['localhost']['should_install_neovim'] | default(false)

- import_playbook: playbooks/development/lazyvim.yml
  tags: [base, lazyvim]
  when: hostvars['localhost']['should_install_neovim'] | default(false) and hostvars['localhost']['should_install_lazyvim'] | default(false)

- import_playbook: playbooks/development/lazygit.yml
  tags: [base, lazygit]
  when: hostvars['localhost']['should_install_neovim'] | default(false) and hostvars['localhost']['should_install_lazyvim'] | default(false)

- import_playbook: playbooks/development/fd.yml
  tags: [base, fd]
  when: hostvars['localhost']['should_install_neovim'] | default(false)

# Docker and containers
- import_playbook: playbooks/development/docker.yml
  tags: [base, docker]
  when: hostvars['localhost']['should_install_docker'] | default(false)

- import_playbook: playbooks/development/portainer.yml
  tags: [base, portainer]
  when: hostvars['localhost']['should_install_docker'] | default(false)

# Development tools
- import_playbook: playbooks/development/ast-grep.yml
  tags: [base, ast-grep]
  when: hostvars['localhost']['should_install_ast_grep'] | default(false)

- import_playbook: playbooks/development/tmux.yml
  tags: [base, tmux]
  when: hostvars['localhost']['should_install_tmux'] | default(false)

- import_playbook: playbooks/development/zellij.yml
  tags: [base, zellij]
  when: hostvars['localhost']['should_install_zellij'] | default(false)


- import_playbook: playbooks/development/starship.yml
  tags: [base, starship]
  when: hostvars['localhost']['should_install_starship'] | default(false)

- import_playbook: playbooks/development/rocm.yml
  tags: [base, rocm]
  when: hostvars['localhost']['should_install_rocm'] | default(false)

# Clojure
- import_playbook: playbooks/development/rlwrap.yml
  tags: [base, clojure, rlwrap]
  when: hostvars['localhost']['should_install_clojure'] | default(false)

- import_playbook: playbooks/development/babashka.yml
  tags: [base, clojure, babashka]
  when: hostvars['localhost']['should_install_clojure'] | default(false)

- import_playbook: playbooks/development/clojure-cli.yml
  tags: [base, clojure, clojure-cli]
  when: hostvars['localhost']['should_install_clojure'] | default(false)

# Game development
- import_playbook: playbooks/development/odin.yml
  tags: [base, odin]
  when: hostvars['localhost']['should_install_game_dev'] | default(false)

- import_playbook: playbooks/development/blockbench.yml
  tags: [base, blockbench]
  when: hostvars['localhost']['should_install_game_dev'] | default(false)

# Applications
- import_playbook: playbooks/applications/chromium.yml
  tags: [base, chromium]
  when: hostvars['localhost']['should_install_chromium'] | default(false)

- import_playbook: playbooks/applications/speedcrunch.yml
  tags: [base, speedcrunch]
  when: hostvars['localhost']['should_install_speedcrunch'] | default(false)

# Keyboard shortcuts
- import_playbook: playbooks/keyboard-shortcuts/soeren.yml
  tags: [base, keyboard-shortcuts]
  when: hostvars['localhost']['should_install_keyboard_shortcuts'] | default(false)
