---
- name: ast-grep
  hosts: localhost

  tasks:
    - name: Install ast-grep
      become: yes
      become_method: sudo
      community.general.pacman:
        name: ast-grep
        state: present
