---
- name: Doom Emacs Tool Dependencies (Soeren)
  hosts: localhost

  tasks:
    - name: Gather facts
      setup:

    - name: Install tool dependencies (Ubuntu/Debian)
      become: yes
      become_method: sudo
      apt:
        name:
          - shellcheck
          - pipenv
          - python3-pytest
          - pandoc
          - shfmt
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install tool dependencies (Fedora)
      become: yes
      become_method: sudo
      dnf:
        name:
          - ShellCheck
          - pipenv
          - python3-pytest
          - pandoc
          - shfmt
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Python tools via pipx
      command: "pipx install {{ item }}"
      loop:
        - grip
        - isort
        - nose
        - black
      register: pipx_install
      changed_when: "'installed package' in pipx_install.stdout"
      failed_when: pipx_install.rc != 0 and 'already' not in pipx_install.stdout
