return {
  "eraserhd/parinfer-rust",
  build = "PATH=$HOME/.cargo/bin:$PATH cargo build --release",
  ft = {
    "clojure",
    "clojurescript",
    "cljc",
    "scheme",
    "lisp",
    "racket",
    "hy",
    "fennel",
    "janet",
    "carp",
    "wast",
    "yuck",
    "dune",
    "edn",
    "bb",
  },
}
